### ISSUE TITLE
You can create uppercase urls and when you access with uppercase url redirect gets crazy.

### ISSUE THREAD

**Issue by sielay** [getlackey/lackey-cms#78]
# You can create uppercase urls and when you access with uppercase url redirect gets crazy.

## Type

 * Bug

## Environment

 * Version: 0.9.*

## Expected behaviour

 

- [ ] * All urls should be lowercase
- [x]  * Uppercase requests should be redirected to lowercase

## Actual behaviour

 * If you create uppercase URL you'd get 404
 * There is no 404 working properly
 * If you access lowercase URL with uppercase you get infinite redirection

## Notes

**Comment by melono6** [comment]
"Uppercase requests should be redirected to lowercase" fixed in #106

**Comment by melono6** [comment]
"* All urls should be lowercase"
are we preventing users from submitting urls with uppercase letters or converting them to lowercase when submitted? @sielay

**Comment by sielay** [comment]
@melono6 as you can always "break" or "cheat" JS on frontend, I'd do both.

**Comment by melono6** [comment]
fixed in #115
